# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

isLittleEndian <- function() {
    .Call(`_farray_isLittleEndian`)
}

loc2idx3 <- function(locations, parent_dim) {
    .Call(`_farray_loc2idx3`, locations, parent_dim)
}

parseSlices <- function(listOrEnv, dim, pos_subscript = TRUE) {
    .Call(`_farray_parseSlices`, listOrEnv, dim, pos_subscript)
}

parseAndScheduleBlocks2 <- function(sliceIdx, dim, forceSchedule = FALSE) {
    .Call(`_farray_parseAndScheduleBlocks2`, sliceIdx, dim, forceSchedule)
}

reshapeOrDrop <- function(x, reshape = NULL, drop = FALSE) {
    .Call(`_farray_reshapeOrDrop`, x, reshape, drop)
}

setFArrayBlockSize <- function(size, limit = 0L, buf_size = 0L) {
    .Call(`_farray_setFArrayBlockSize`, size, limit, buf_size)
}

getFArrayBlockSize <- function(which = 0L) {
    .Call(`_farray_getFArrayBlockSize`, which)
}

subsetFM <- function(rootPath, listOrEnv, dim, dtype, reshape, drop) {
    .Call(`_farray_subsetFM`, rootPath, listOrEnv, dim, dtype, reshape, drop)
}

getFArrayThread <- function(max = FALSE) {
    .Call(`_farray_getFArrayThread`, max)
}

setFArrayThread <- function(n, reset_after_fork = NULL) {
    .Call(`_farray_setFArrayThread`, n, reset_after_fork)
}

hasOpenMP <- function() {
    .Call(`_farray_hasOpenMP`)
}

cpp_writeBin2 <- function(file, data, skip = 0L) {
    .Call(`_farray_cpp_writeBin2`, file, data, skip)
}

subsetAssignFM <- function(rootPath, listOrEnv, dim, data) {
    .Call(`_farray_subsetAssignFM`, rootPath, listOrEnv, dim, data)
}

dropDimension <- function(x) {
    .Call(`_farray_dropDimension`, x)
}

prod2 <- function(x, na_rm = FALSE) {
    .Call(`_farray_prod2`, x, na_rm)
}

parseDots <- function(env, eval) {
    .Call(`_farray_parseDots`, env, eval)
}

stopIfNot <- function(isValid, message, stopIfError = TRUE) {
    .Call(`_farray_stopIfNot`, isValid, message, stopIfError)
}

getSexpType <- function(x) {
    .Call(`_farray_getSexpType`, x)
}

tik <- function() {
    .Call(`_farray_tik`)
}

tok <- function(msg, stop = FALSE) {
    .Call(`_farray_tok`, msg, stop)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_farray_RcppExport_registerCCallable', PACKAGE = 'farray')
})
