# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loc2idx <- function(locations, dim) {
    .Call(`_farray_loc2idx`, locations, dim)
}

listOrEnv2Idx2 <- function(listOrEnv, dim, bDim) {
    .Call(`_farray_listOrEnv2Idx2`, listOrEnv, dim, bDim)
}

